#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_MAJOR 0
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_MINOR 6
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_RELEASE 4


#define NVIDIA_VIDEOEFFECTS_SDK_VERSION 0,6,4,0
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_MAJOR_MINOR 0,6
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_STRING "0.6.4.0"
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_STRING_SHORT "0.6.4"
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_STRING_MAJOR_MINOR "0.6"
