#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_MAJOR 0
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_MINOR 5
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_RELEASE 1


#define NVIDIA_VIDEOEFFECTS_SDK_VERSION 0,5,1,0
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_MAJOR_MINOR 0,5
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_STRING "0.5.1.0"
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_STRING_SHORT "0.5.1"
#define NVIDIA_VIDEOEFFECTS_SDK_VERSION_STRING_MAJOR_MINOR "0.5"
